spring:
  application:
    name: spring-erp-platform

  # Configuration de la base de données (isolée sur le port 5433)
  datasource:
    url: jdbc:postgresql://localhost:5433/erp_db
    username: ***REMOVED***
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver

  # Configuration JPA / Hibernate
  jpa:
    hibernate:
      # 'update' crée les tables si elles n'existent pas, idéal pour ce premier lancement
      ddl-auto: validate
    show-sql: true # On active les logs SQL pour voir la création des tables
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuration Flyway (désactivée temporairement pour laisser Hibernate créer les tables)
  flyway:
    enabled: false

server:
  port: 8080

# Paramètres personnalisés pour le JWT
app:
  jwt:
    # Clé de 256 bits
    secret: ***REMOVED***
    # Expiration : 24 heures
    expiration: 86400000

# Actuator pour monitorer l'état de l'app
management:
  endpoints:
    web:
      exposure:
        include: health,info